# Generated by Django 2.0.6 on 2018-10-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0002_auto_20181009_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextMessage1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talker1', models.CharField(max_length=10)),
                ('message1', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
