# Generated by Django 2.0.6 on 2018-10-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0003_textmessage1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmessage',
            name='message',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='textmessage',
            name='talker',
            field=models.CharField(max_length=20),
        ),
    ]
