# Generated by Django 2.0.6 on 2018-10-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0004_auto_20181015_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='TextMessage1',
        ),
    ]
